server:
  shutdown: graceful
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/liquibase.changelog.xml
    url: jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}